#pragma once
#include <stdint.h>

enum seL4EmuErrorType {
  SEL4EMU_INIT_NOERROR = 0,
  SEL4EMU_INIT_SOCK_FAILED,
  SEL4EMU_INIT_CONNECT_FAILED,
  SEL4EMU_INIT_RD_FAILED,
  SEL4EMU_INIT_WR_FAILED,
  SEL4EMU_INIT_BIMMAP_FAILED,
  SEL4EMU_INIT_IPCBUFMMAP_FAILED,
  SEL4EMU_INIT_SIGNAL_FAILED,
  SEL4EMU_MMAP_FAILED,
} ;

typedef uint64_t seL4emu_err_t;